blank_issues_enabled: false
contact_links:
  - name: Question?
    url: https://github.com/xgauravyaduvanshii/shrinking-server/issues
    about: Open an issue on shrinking-server for setup help, bugs, or questions
